#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ebin

main(_) ->
  ok = application:start(logdb),
  {ok, Popo} = logdb:new(popo),
  ok = logdb:append(Popo, 42, {an_atom, 4807}),
  ok = logdb:append(Popo, 43, {oups, "Some string"}).
